# Generated by Django 4.1.2 on 2022-12-05 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_pw_userprofile_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='username',
            new_name='name',
        ),
    ]
