# Generated by Django 4.1.2 on 2022-12-07 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_course_instructor_remove_section_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='assignedTo',
        ),
        migrations.AddField(
            model_name='section',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.userprofile'),
        ),
    ]
