# Generated by Django 4.1.2 on 2022-12-07 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_userprofile_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='id',
            new_name='CourseId',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='id',
            new_name='SectionId',
        ),
    ]
