# Generated by Django 4.1.2 on 2022-12-22 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_course_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=20, unique=True),
        ),
    ]
